export * from "./auth.js";
export * from "./curriculum.js";
export * from "./assignments.js";
export * from "./feedback.js";
export * from "./quiz.js";
export * from "./misc.js";
export * from "./playlist.js";
export * from "./certificate.js";
export * from "./booking.js";
